from __future__ import annotations
from typing import List, Protocol, Tuple, Any, runtime_checkable
from helpers.ADRS import ADRS

@runtime_checkable
class WOTSLike(Protocol):
    last_counter: bytes
    def wots_PKgen(self, sk_seed: bytes, pk_seed: bytes, adrs: ADRS, /) -> bytes: ...
    def wots_sign(self, M: bytes, sk_seed: bytes, pk_seed: bytes, adrs: ADRS, /) -> List[bytes]: ...
    def wots_pkFromSig(self, sig: List[bytes], M: bytes, pk_seed: bytes, adrs: ADRS, /) -> bytes: ...
    def sig_from_bytes(self, data: bytes, /) -> List[bytes]: ...
    def set_counter(self, counter_bytes: bytes, /) -> None: ...

@runtime_checkable
class PKLike(Protocol):
    pk_seed: bytes
    pk_root: bytes

@runtime_checkable
class SphincsLike(Protocol):
    def spx_keygen(self) -> Tuple[Any, Any]: ...
    def spx_sign(self, message: bytes, sk: Any, /) -> bytes: ...
    def spx_verify(self, message: bytes, SIG: bytes, pk: Any, /) -> bool: ...